# Nom du workflow - identifie ce workflow parmi d'autres dans le projet
name: Test Suite

on:
  push:
    branches:
      - "dev"

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Ensure Cache Directory
        run: mkdir -p .yarn/cache

      - name: Cache Yarn Modules
        id: cache-yarn-modules
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
            ~/.yarn
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install dependencies
        if: steps.cache-yarn-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run Tests
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: npx hardhat test
