name: Test and Analyze Smart Contracts

on:
  push:
    branches:
      - "dev"

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2 : Installation de Python pour Slither
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Étape 3 : Installation de Slither et du compilateur Solidity
      - name: Install Slither and Solidity Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc
          pip install slither-analyzer

      # Étape 4 : Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      # Étape 5 : Gestion du cache des dépendances Yarn
      - name: Cache Yarn Modules
        id: cache-yarn-modules  # Identifiant unique pour cette étape, utilisé pour la condition de l'étape suivante
        uses: actions/cache@v2  # Utilise l'action de cache officielle de GitHub
        with:
          path: .yarn/cache  # Chemin des fichiers à mettre en cache
          key: yarn-cache-${{ hashFiles('yarn.lock') }}  # Clé unique basée sur le contenu de yarn.lock

      # Étape 6 : Installation des dépendances avec Yarn
      - name: Install Dependencies
        if: steps.cache-yarn-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      # Étape 7 : Nettoyage des contrats
      - name: Run Hardhat Clean
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: yarn hardhat clean

      # Étape 8 : Compilation des contrats
      - name: Compile Contracts
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: yarn hardhat compile

      # Étape 9 : Analyse avec Slither
      - name: Run Slither Analysis
        run: slither . || true

      # Étape 10 : Exécution des tests Hardhat
      - name: Run Hardhat Tests
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: yarn hardhat test
