name: Test and Analyze Smart Contracts

on:
  push:
    branches:
      - "dev"

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Solidity Compiler (solc)
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc

      - name: Install Slither and dependencies
        run: pip install slither-analyzer

      - name: Run Slither Analysis
        run: |
          slither . --config-file slither.config.json || true

      - name: Use Node.js 22.11.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Cache Yarn Modules
        id: cache-yarn-modules
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
            ~/.yarn
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install dependencies
        if: steps.cache-yarn-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run Hardhat Tests
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: npx hardhat test
